postgres:
  database: users-1
  user: postgres
  password: root
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

host: 127.0.0.1
port: 8080

jwt:
  secret: jwt-secret
  access_token_living_minutes: 30
  refresh_token_living_days: 14
  algorithm: HS256
  request_property: payload
  auth_scheme: Bearer